sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=7d35e8f9ec6302498cfa3d55dd4c1c2596420c0d8a99d4285e326434fcd2c033
language: ruby
rvm:
  - 2.4.1
  - 2.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_install: gem install bundler -v 1.13.6
branches:
  only:
    - master